/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData notifications_none = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData subdirectory_arrow_right = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chart_bar = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData timer = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData error = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData wrench = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData target = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData hourglass_full = const IconData(0xe808, fontFamily: _kFontFam);
}
